# BROWSER USED FOR SCRIPT
browser=chrome
# APPLICATION TO BE LAUNCH
url=https://www.demoblaze.com/
# APPLICATION LOGIN CREDENTIALS
username=Natesh@23
password=Enatesh@23
screenshot=.//Screenshot//
#ORDER PLACING DETAILS
name=Nateshkumar
country=India
city=Chennai
creditCard=1234567890123
month=04
year=2027
